---
title: "Sentinel 2 TopCor"
author: "Marvin Ludwig"
date: "21/05/2020"
output: html_document
---


## Sentinel 2 Topografic Correction Workflow

### Extract Sun Angle and Sun Azimuth from Sentinel 2 Metadata

> Filepath: `S2.SAFE/GRANULE/L2A_T32UMB_A024844_20200325T103018/MTD_TL.xml`


```{r, eval = FALSE}
library(XML)

metafile = "path to metafile"

meta = XML::xmlParse(metafile)
meta = XML::xmlToList(meta)


# Sun Angle
sun_angle = meta$Geometric_Info$Tile_Angles$Mean_Sun_Angle$ZENITH_ANGLE

# Azimuth Angle
sun_azimuth = meta$Geometric_Info$Tile_Angles$Mean_Sun_Angle$AZIMUTH_ANGLE

```


### Create Hillshade

* Create a DEM from the Lidar Data with the Sentinel Tile as the grid basis (10 x 10 m)
* Maybe SRTM is also sufficient
* calculate a hillshade with the extracted sun angle and azimuth

```{r, eval = FALSE}

library(raster)

dem = raster("pathToDem")

hs = raster::hillShade(slope = raster::terrain(dem, opt = "slope"),
                       aspect = raster::terrain(dem, opt = "aspect"),
                       angle = sun_angle,
                       direction = sun_azimuth)


```


### Topografic Correction

```{r, eval = FALSE}

library(satellite)

sen = stack("pathToSentinel")
tc <- satellite::calcTopoCorr(sen, hs)

```




